services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64 # if on Apple Silicon
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posts_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    container_name: node_backend
    build:
      context: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4001:4001"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules

  # frontend:
  #   container_name: react_frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./frontend/.env
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  frontend_vite:
    container_name: frontend_vite
    build:
      context: ./frontend_vite
    ports:
      - "5173:5173"
    env_file:
      - ./frontend_vite/.env
    depends_on:
      - backend
    volumes:
      - ./frontend_vite:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:
